### ISSUE TITLE
[BUG] Android CPP code fails to compile on Windows 11 Android Studio (2022.3.1. Patch 2)

### ISSUE THREAD

**Issue by krackjack234** [android/ndk#1946]
### Description

We are unable to build CPP code on Android Studio Giraffe (2022.3.1 Patch 2) along with java code
The NDK version used is 26.0.10792818 and CMAKE version is 3.22.1

Below are the errors we are getting

```
use of undeclared identifier 'xW2yrwm1J9wvEEpODJGGBfnIx4b9FjlGuC0y3oJNpO4dPfZ3lvRGQZ' [armeabi-v7a]
use of undeclared identifier 'V' [armeabi-v7a]
invalid suffix 'q8OMtgR1pKQNDdVKmXxImrQmUK7yZ3mZhfpfUZeqg9' on integer constant [armeabi-v7a]
use of undeclared identifier 'yCn'; did you mean 'yn'? [armeabi-v7a]
use of undeclared identifier 'm33x6By7OspgRlwXEtDdB' [armeabi-v7a]
use of undeclared identifier 'bFxIr6EDQK4iF2l5wNoaJJe' [armeabi-v7a]
```

### Affected versions

r26

### Host OS

Windows

### Host OS version

Windows 11

### Affected ABIs

x86_64

### Build system

CMake

### minSdkVersion

android 21

**Comment by DanAlbert** [comment]
There's nothing we can do without a repro case. The error messages make me suspect you'll find the problem yourself just by trying to minimize the repro case though. You've either got some obfuscation crap that's not being used correctly, or something is seriously wrong with your build config.
