### ISSUE TITLE
[question/might be a BUG] AAudio.h:809:9: error: unknown type name 'bool' in NDK 21d

### ISSUE THREAD

**Issue by planethcom** [android/ndk#1281]
Since NDK 21d (21.3.6528147), I'm getting the following compiler error:

.....\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\include\aaudio\AAudio.h:809:9: error: unknown type name 'bool'

The same setup worked well with NDK 21c (21.2.6472646) and below.
Any help would be welcome.
Thanks in advance

**Comment by enh-google** [comment]
i note that although many of our header files use `bool` almost none of them `#include <stdbool.h>` so they'll work from C as well as C++ source.

<math.h> is a false positive (it mentions `bool` in a comment), and others get <stdbool.h> via transitive include, but this gives an idea:
```
--- /tmp/uses-bool	2020-06-12 08:12:21.000000000 -0700
+++ /tmp/includes-stdbool	2020-06-12 08:12:35.000000000 -0700
@@ -1,22 +1,12 @@
-./EGL/Platform.h
-./android/NeuralNetworks.h
-./android/binder_auto_utils.h
-./android/binder_ibinder.h
-./android/binder_interface_utils.h
-./android/binder_parcel.h
-./android/binder_parcel_utils.h
-./android/binder_status.h
+./android/dlext.h
+./android/fdsan.h
 ./android/font.h
 ./android/font_matcher.h
 ./android/sensor.h
+./android/system_fonts.h
 ./android/trace.h
 ./bits/stdatomic.h
 ./camera/NdkCameraCaptureSession.h
-./camera/NdkCameraMetadata.h
-./math.h
-./media/NdkMediaCodec.h
 ./media/NdkMediaCrypto.h
 ./media/NdkMediaDrm.h
-./media/NdkMediaExtractor.h
-./media/NdkMediaFormat.h
 ./sys/system_properties.h
```
(the + lines are files that include <stdbool.h> but don't use bool. of course we have some of them too.)

**Comment by enh-google** [comment]
(just to be explicit: your short-term workaround is `#include <stdbool.h>` before you include AAudio.h.)

**Comment by planethcom** [comment]
> (just to be explicit: your short-term workaround is #include <stdbool.h> before you include AAudio.h.)

That worked well, at least as a workaround for now. 
Thanks a lot

**Comment by enh-google** [comment]
ndk_binder: https://android-review.googlesource.com/c/platform/frameworks/native/+/1331456

camera & media: https://android-review.googlesource.com/c/platform/frameworks/av/+/1333894

nnapi: https://android-review.googlesource.com/c/platform/frameworks/ml/+/1333955

the audio API isn't in AOSP yet, so the CL for that is internal: https://googleplex-android-review.git.corp.google.com/c/platform/frameworks/av/+/11851227

**Comment by planethcom** [comment]
Thank you very much for the prompt reaction. Much appreciated!

**Comment by philburk** [comment]
> the audio API isn't in AOSP yet

AAudio is in AOSP at:
https://android.googlesource.com/platform/frameworks/av/+/refs/heads/master/media/libaaudio/include/aaudio

**Comment by enh-google** [comment]
> > the audio API isn't in AOSP yet
> 
> AAudio is in AOSP at:
> https://android.googlesource.com/platform/frameworks/av/+/refs/heads/master/media/libaaudio/include/aaudio

aye, but the specific new API that uses bool isn't in AOSP yet :-)

**Comment by DanAlbert** [comment]
I think the patches that fix this are in now so I just need to merge them into the r21 sysroot and make the update.

**Comment by philburk** [comment]
I see that stdbool.h was added to AAudio.h in this CL on June 12, 2020:

https://android.googlesource.com/platform/frameworks/av/+/9c1fca20c31ad0442e6be8d665dedb2c419a6093%5E%21/#F0

**Comment by DanAlbert** [comment]
> I am hitting it with NDK 21.3.6528147.

Because that's too old: https://github.com/android/ndk/wiki/Changelog-r21#r21e

You're using r21d.
